# Generated by Django 4.0.4 on 2022-10-18 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_lecture_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.lecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='_course',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='classes.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='lecture',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.lecture'),
            preserve_default=False,
        ),
    ]
